---
title: "Links"
output: html_document
---

# Conclusion

From the animation, it is observed that rainfall has increased a lot from April to July. The high frequency of rain in September can also be noticed. To summarize, we can say that the changing climate and increase in temperature (especially increase in minimum temperature) has a profound impact on increase in rainfall intensity. Due to this sudden increase in rain intensity coupled with rising sea levels, Bangladesh has seen a rise in frequent floods both in internal and coastal parts of the country. 

# Reference

Basak, J. K., Titumir, R. A. M., & Dey, N. C. (2013). Climate change in Bangladesh: a historical analysis of temperature and rainfall data. Journal of Environment, 2(2), 41-46.

Huq, S. (2001). Climate change and Bangladesh. Science, 294(5547), 1617-1618.

Huq, S., Karim, Z., & Asaduzzaman, M. (1999). Vulnerability and adaptation to climate change for Bangladesh.

Mahmood, S. A. I. (2012). Impact of climate change in Bangladesh: The role of public administration and government’s integrity. Journal of Ecology and the Natural Environment, 4(8), 223-240.

Shahid, S. (2010). Recent trends in the climate of Bangladesh. Climate Research, 42(3), 185-193.

Shahid, S. (2011). Trends in extreme rainfall events of Bangladesh. Theoretical and applied climatology, 104(3), 489-499.


# ShinyApp Link
### [https://uddaydatta.shinyapps.io/Changing_Weather/](https://uddaydatta.shinyapps.io/Changing_Weather/)